# DataFrame에 있는 데이터 그룹핑해서 보기

In [1]:
import pandas as pd

#### groupby
  + 데이터를 그룹화(groupping)
  + SQL의 group by와 동일한 개념

In [2]:
marathon_2017 = pd.read_csv("marathon_results_2017.csv")
marathon_2017.head()

,Unnamed: 0,Bib,Name,Age,M/F,City,State,Country,Citizen,Unnamed: 9,...,25K,30K,35K,40K,Pace,Proj Time,Official Time,Overall,Gender,Division
0,0,11,"Kirui, Geoffrey",24,M,Keringet,NaN,KEN,NaN,NaN,...,1:16:59,1:33:01,1:48:19,2:02:53,0:04:57,-,2:09:37,1,1,1
1,1,17,"Rupp, Galen",30,M,Portland,OR,USA,NaN,NaN,...,1:16:59,1:33:01,1:48:19,2:03:14,0:04:58,-,2:09:58,2,2,2
2,2,23,"Osako, Suguru",25,M,Machida-City,NaN,JPN,NaN,NaN,...,1:17:00,1:33:01,1:48:31,2:03:38,0:04:59,-,2:10:28,3,3,3
3,3,21,"Biwott, Shadrack",32,M,Mammoth Lakes,CA,USA,NaN,NaN,...,1:17:00,1:33:01,1:48:58,2:04:35,0:05:03,-,2:12:08,4,4,4
4,4,9,"Chebet, Wilson",31,M,Marakwet,NaN,KEN,NaN,NaN,...,1:16:59,1:33:01,1:48:41,2:05:00,0:05:04,-,2:12:35,5,5,5

In [3]:
marathon_2017.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26410 entries, 0 to 26409
Data columns (total 25 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Unnamed: 0     26410 non-null  int64
 1   Bib            26410 non-null  object
 2   Name           26410 non-null  object
 3   Age            26410 non-null  int64
 4   M/F            26410 non-null  object
 5   City           26410 non-null  object
 6   State          22815 non-null  object
 7   Country        26410 non-null  object
 8   Citizen        1254 non-null   object
 9   Unnamed: 9     91 non-null     object
 10  5K             26410 non-null  object
 11  10K            26410 non-null  object
 12  15K            26410 non-null  object
 13  20K            26410 non-null  object
 14  Half           26410 non-null  object
 15  25K            26410 non-null  object
 16  30K            26410 non-null  object
 17  35K            26410 non-null  object
 18  40K            26410 non-null  object
 19  Pace           26410 non-null  object
 20  Proj Time      26410 non-null  object
 21  Official Time  26410 non-null  object
 22  Overall        26410 non-null  int64
 23  Gender         26410 non-null  int64
 24  Division       26410 non-null  int64
dtypes: int64(5), object(20)
memory usage: 5.0+ MB

#### 그룹핑된 데이터의 groups 속성
 - 각 그룹과 그룹에 속한 index를 dictionary로 표현

#### 단일 column으로 그룹핑

In [4]:
gender_group = marathon_2017.groupby('M/F')
gender_group

In [5]:
gender_group.groups  # dictionary로 표현

{'F': [20, 23, 24, 33, 43, 53, 62, 69, 74, 84, 94, 97, 109, 114, 117, 119, 133, 147, 157, 159, 186, 189, 210, 230, 267, 280, 301, 358, 366, 381, 418, 448, 455, 468, 479, 501, 507, 552, 597, 604, 679, 706, 717, 751, 768, 777, 806, 840, 843, 886, 904, 942, 943, 971, 972, 981, 1001, 1029, 1036, 1048, 1054, 1069, 1073, 1080, 1094, 1102, 1104, 1119, 1122, 1131, 1140, 1145, 1155, 1159, 1162, 1191, 1201, 1236, 1264, 1272, 1282, 1293, 1300, 1302, 1322, 1343, 1365, 1370, 1373, 1396, 1425, 1439, 1464, 1471, 1472, 1476, 1477, 1491, 1515, 1554, ...], 'M': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 21, 22, 25, 26, 27, 28, 29, 30, 31, 32, 34, 35, 36, 37, 38, 39, 40, 41, 42, 44, 45, 46, 47, 48, 49, 50, 51, 52, 54, 55, 56, 57, 58, 59, 60, 61, 63, 64, 65, 66, 67, 68, 70, 71, 72, 73, 75, 76, 77, 78, 79, 80, 81, 82, 83, 85, 86, 87, 88, 89, 90, 91, 92, 93, 95, 96, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 110, 111, 112, ...]}

#### 그룹핑된 데이터와 함께 사용되는 통계함수
 - NaN 값은 제외하고 연산
 - count - 데이터 개수
 - sum   - 데이터의 합
 - mean, std, var - 평균, 표준편차, 분산
 - min, max - 최소, 최대값

In [6]:
gender_group.count()

,Unnamed: 0,Bib,Name,Age,City,State,Country,Citizen,Unnamed: 9,5K,...,25K,30K,35K,40K,Pace,Proj Time,Official Time,Overall,Gender,Division
M/F,,,,,,,,,,,,,,,,,,,,,
F,11972,11972,11972,11972,11972,10972,11972,417,24,11972,...,11972,11972,11972,11972,11972,11972,11972,11972,11972,11972
M,14438,14438,14438,14438,14438,11843,14438,837,67,14438,...,14438,14438,14438,14438,14438,14438,14438,14438,14438,14438

In [11]:
gender_group['Age'].mean()

M/F
F    39.952974
M    44.772475
Name: Age, dtype: float64

In [12]:
marathon_2017[marathon_2017['Country']=='KEN'].groupby('M/F')['Age'].mean()

M/F
F    29.25
M    30.25
Name: Age, dtype: float64

#### 복수개의 column으로 그룹핑
 - groupby에 column 리스트를 전달
 - 통계함수를 적용한 결과는 multiindex를 갖는 DataFrame

In [13]:
marathon_2017.groupby(['Country', 'M/F'])['Age'].mean()

Country  M/F
ALG      M      54.500000
AND      M      58.000000
ARG      F      44.454545
         M      48.480000
AUS      F      42.774648
                  ...
USA      F      39.262085
         M      44.089359
VEN      F      32.000000
         M      46.250000
ZIM      M      34.000000
Name: Age, Length: 157, dtype: float64

In [14]:
marathon_2017.groupby(['Country', 'M/F'])['Age'].mean().loc[('VEN', 'F')]

32.0

In [16]:
marathon_2017.groupby(['Country', 'M/F'])['Age'].mean().index

MultiIndex([('ALG', 'M'),
            ('AND', 'M'),
            ('ARG', 'F'),
            ('ARG', 'M'),
            ('AUS', 'F'),
            ('AUS', 'M'),
            ('AUT', 'F'),
            ('AUT', 'M'),
            ('BAR', 'F'),
            ('BDI', 'F'),
            ...
            ('UAE', 'M'),
            ('UKR', 'F'),
            ('UKR', 'M'),
            ('URU', 'F'),
            ('URU', 'M'),
            ('USA', 'F'),
            ('USA', 'M'),
            ('VEN', 'F'),
            ('VEN', 'M'),
            ('ZIM', 'M')],
           names=['Country', 'M/F'], length=157)

#### index를 이용한 그룹핑
  - index가 있는 경우, groupby 함수에 level 사용 가능
  - level은 index의 depth를 의미하며, 가장 왼쪽부터 0부터 증가
  - **set_index** 함수
    - column을 index 레벨로 변경
  - **reset_index** 함수
    - index 초기화

In [ ]:
marathon_2017.head()

,Unnamed: 0,Bib,Name,Age,M/F,City,State,Country,Citizen,Unnamed: 9,...,25K,30K,35K,40K,Pace,Proj Time,Official Time,Overall,Gender,Division
0,0,11,"Kirui, Geoffrey",24,M,Keringet,NaN,KEN,NaN,NaN,...,1:16:59,1:33:01,1:48:19,2:02:53,0:04:57,-,2:09:37,1,1,1
1,1,17,"Rupp, Galen",30,M,Portland,OR,USA,NaN,NaN,...,1:16:59,1:33:01,1:48:19,2:03:14,0:04:58,-,2:09:58,2,2,2
2,2,23,"Osako, Suguru",25,M,Machida-City,NaN,JPN,NaN,NaN,...,1:17:00,1:33:01,1:48:31,2:03:38,0:04:59,-,2:10:28,3,3,3
3,3,21,"Biwott, Shadrack",32,M,Mammoth Lakes,CA,USA,NaN,NaN,...,1:17:00,1:33:01,1:48:58,2:04:35,0:05:03,-,2:12:08,4,4,4
4,4,9,"Chebet, Wilson",31,M,Marakwet,NaN,KEN,NaN,NaN,...,1:16:59,1:33:01,1:48:41,2:05:00,0:05:04,-,2:12:35,5,5,5

In [ ]:
marathon_2017.set_index('Country')  # Country 를 인덱스로 지정

,Unnamed: 0,Bib,Name,Age,M/F,City,State,Citizen,Unnamed: 9,5K,...,25K,30K,35K,40K,Pace,Proj Time,Official Time,Overall,Gender,Division
Country,,,,,,,,,,,,,,,,,,,,,
KEN,0,11,"Kirui, Geoffrey",24,M,Keringet,NaN,NaN,NaN,0:15:25,...,1:16:59,1:33:01,1:48:19,2:02:53,0:04:57,-,2:09:37,1,1,1
USA,1,17,"Rupp, Galen",30,M,Portland,OR,NaN,NaN,0:15:24,...,1:16:59,1:33:01,1:48:19,2:03:14,0:04:58,-,2:09:58,2,2,2
JPN,2,23,"Osako, Suguru",25,M,Machida-City,NaN,NaN,NaN,0:15:25,...,1:17:00,1:33:01,1:48:31,2:03:38,0:04:59,-,2:10:28,3,3,3
USA,3,21,"Biwott, Shadrack",32,M,Mammoth Lakes,CA,NaN,NaN,0:15:25,...,1:17:00,1:33:01,1:48:58,2:04:35,0:05:03,-,2:12:08,4,4,4
KEN,4,9,"Chebet, Wilson",31,M,Marakwet,NaN,NaN,NaN,0:15:25,...,1:16:59,1:33:01,1:48:41,2:05:00,0:05:04,-,2:12:35,5,5,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
USA,26405,25166,"Steinbach, Paula Eyvonne",61,F,Ontario,CA,NaN,MI,0:46:44,...,4:12:06,5:03:08,5:55:18,6:46:57,0:16:24,-,7:09:39,26407,11972,344
USA,26406,25178,"Avelino, Andrew R.",25,M,Fayetteville,NC,NaN,MI,0:32:03,...,3:50:19,4:50:01,5:53:48,6:54:21,0:16:40,-,7:16:59,26408,14436,4774
USA,26407,27086,"Hantel, Johanna",57,F,Malvern,PA,NaN,NaN,0:53:11,...,4:15:21,5:06:37,6:00:33,6:54:38,0:16:47,-,7:19:37,26409,11973,698
USA,26408,25268,"Reilly, Bill",64,M,New York,NY,NaN,MI,0:40:34,...,4:06:10,5:07:09,6:06:07,6:56:08,0:16:49,-,7:20:44,26410,14437,1043
USA,26409,25266,"Rigsby, Scott",48,M,Alpharetta,GA,NaN,MI,0:39:36,...,4:27:14,5:37:13,6:39:07,7:41:23,0:18:15,-,7:58:14,26411,14438,2553

In [ ]:
marathon_2017.set_index(['Country', 'M/F'])  # Country 와 M/F 을 멀티 인덱스로 지정

             Unnamed: 0    Bib                      Name  Age           City  \
Country M/F
KEN     M             0     11           Kirui, Geoffrey   24       Keringet
USA     M             1     17               Rupp, Galen   30       Portland
JPN     M             2     23             Osako, Suguru   25   Machida-City
USA     M             3     21          Biwott, Shadrack   32  Mammoth Lakes
KEN     M             4      9            Chebet, Wilson   31       Marakwet
...                 ...    ...                       ...  ...            ...
USA     F         26405  25166  Steinbach, Paula Eyvonne   61        Ontario
        M         26406  25178        Avelino, Andrew R.   25   Fayetteville
        F         26407  27086           Hantel, Johanna   57        Malvern
        M         26408  25268              Reilly, Bill   64       New York
        M         26409  25266             Rigsby, Scott   48     Alpharetta

            State Citizen Unnamed: 9       5K      10K  ...      25K      30K  \
Country M/F                                             ...
KEN     M     NaN     NaN        NaN  0:15:25  0:30:28  ...  1:16:59  1:33:01
USA     M      OR     NaN        NaN  0:15:24  0:30:27  ...  1:16:59  1:33:01
JPN     M     NaN     NaN        NaN  0:15:25  0:30:29  ...  1:17:00  1:33:01
USA     M      CA     NaN        NaN  0:15:25  0:30:29  ...  1:17:00  1:33:01
KEN     M     NaN     NaN        NaN  0:15:25  0:30:28  ...  1:16:59  1:33:01
...           ...     ...        ...      ...      ...  ...      ...      ...
USA     F      CA     NaN         MI  0:46:44  1:35:41  ...  4:12:06  5:03:08
        M      NC     NaN         MI  0:32:03  1:05:33  ...  3:50:19  4:50:01
        F      PA     NaN        NaN  0:53:11  1:43:36  ...  4:15:21  5:06:37
        M      NY     NaN         MI  0:40:34  1:27:19  ...  4:06:10  5:07:09
        M      GA     NaN         MI  0:39:36  1:17:12  ...  4:27:14  5:37:13

                 35K      40K     Pace Proj Time Official Time Overall Gender  \
Country M/F
KEN     M    1:48:19  2:02:53  0:04:57         -       2:09:37       1      1
USA     M    1:48:19  2:03:14  0:04:58         -       2:09:58       2      2
JPN     M    1:48:31  2:03:38  0:04:59         -       2:10:28       3      3
USA     M    1:48:58  2:04:35  0:05:03         -       2:12:08       4      4
KEN     M    1:48:41  2:05:00  0:05:04         -       2:12:35       5      5
...              ...      ...      ...       ...           ...     ...    ...
USA     F    5:55:18  6:46:57  0:16:24         -       7:09:39   26407  11972
        M    5:53:48  6:54:21  0:16:40         -       7:16:59   26408  14436
        F    6:00:33  6:54:38  0:16:47         -       7:19:37   26409  11973
        M    6:06:07  6:56:08  0:16:49         -       7:20:44   26410  14437
        M    6:39:07  7:41:23  0:18:15         -       7:58:14   26411  14438

            Division
Country M/F
KEN     M          1
USA     M          2
JPN     M          3
USA     M          4
KEN     M          5
...              ...
USA     F        344
        M       4774
        F        698
        M       1043
        M       2553

[26410 rows x 23 columns]

In [ ]:
marathon_2017.set_index(['Country', 'M/F']).reset_index()  # 기본 인덱스로 초기화

,Country,M/F,Unnamed: 0,Bib,Name,Age,City,State,Citizen,Unnamed: 9,...,25K,30K,35K,40K,Pace,Proj Time,Official Time,Overall,Gender,Division
0,KEN,M,0,11,"Kirui, Geoffrey",24,Keringet,NaN,NaN,NaN,...,1:16:59,1:33:01,1:48:19,2:02:53,0:04:57,-,2:09:37,1,1,1
1,USA,M,1,17,"Rupp, Galen",30,Portland,OR,NaN,NaN,...,1:16:59,1:33:01,1:48:19,2:03:14,0:04:58,-,2:09:58,2,2,2
2,JPN,M,2,23,"Osako, Suguru",25,Machida-City,NaN,NaN,NaN,...,1:17:00,1:33:01,1:48:31,2:03:38,0:04:59,-,2:10:28,3,3,3
3,USA,M,3,21,"Biwott, Shadrack",32,Mammoth Lakes,CA,NaN,NaN,...,1:17:00,1:33:01,1:48:58,2:04:35,0:05:03,-,2:12:08,4,4,4
4,KEN,M,4,9,"Chebet, Wilson",31,Marakwet,NaN,NaN,NaN,...,1:16:59,1:33:01,1:48:41,2:05:00,0:05:04,-,2:12:35,5,5,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26405,USA,F,26405,25166,"Steinbach, Paula Eyvonne",61,Ontario,CA,NaN,MI,...,4:12:06,5:03:08,5:55:18,6:46:57,0:16:24,-,7:09:39,26407,11972,344
26406,USA,M,26406,25178,"Avelino, Andrew R.",25,Fayetteville,NC,NaN,MI,...,3:50:19,4:50:01,5:53:48,6:54:21,0:16:40,-,7:16:59,26408,14436,4774
26407,USA,F,26407,27086,"Hantel, Johanna",57,Malvern,PA,NaN,NaN,...,4:15:21,5:06:37,6:00:33,6:54:38,0:16:47,-,7:19:37,26409,11973,698
26408,USA,M,26408,25268,"Reilly, Bill",64,New York,NY,NaN,MI,...,4:06:10,5:07:09,6:06:07,6:56:08,0:16:49,-,7:20:44,26410,14437,1043
26409,USA,M,26409,25266,"Rigsby, Scott",48,Alpharetta,GA,NaN,MI,...,4:27:14,5:37:13,6:39:07,7:41:23,0:18:15,-,7:58:14,26411,14438,2553

In [17]:
# index가 한개있으면 level이 0부터 시작. M/F 로 groupby 하여 Age의 평균을 구함.
marathon_2017.set_index('M/F').groupby(level=0)['Age'].mean()

M/F
F    39.952974
M    44.772475
Name: Age, dtype: float64

#### 복수개의 index으로 그룹핑

In [18]:
marathon_2017.set_index(['Country', 'M/F']).groupby(level=[0, 1])['Age'].mean()

Country  M/F
ALG      M      54.500000
AND      M      58.000000
ARG      F      44.454545
         M      48.480000
AUS      F      42.774648
                  ...
USA      F      39.262085
         M      44.089359
VEN      F      32.000000
         M      46.250000
ZIM      M      34.000000
Name: Age, Length: 157, dtype: float64